// PLACEHOLDER — replace by running `flutterfire configure`.
//
// This file is normally generated by the FlutterFire CLI and contains your
// real Firebase project keys. The placeholder values below let the project
// compile; the app will not connect to Firebase until you regenerate it.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return web;
      case TargetPlatform.iOS:
        return web;
      case TargetPlatform.windows:
        return web;
      default:
        return web;
    }
  }

  // Replace these with values from your Firebase console.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsO7Dqeh_VfvC5VCSORlvMQ8Mf2ca05MU',
    appId: '1:825018453020:web:b32185d96e92f0a0c263d9',
    messagingSenderId: '825018453020',
    projectId: 'adazacloud',
    authDomain: 'adazacloud.firebaseapp.com',
    storageBucket: 'adazacloud.firebasestorage.app',
    measurementId: 'G-HRFX9CDDHN',
  );
}
